version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

mysql:
  image: mysql:8.0
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: notifydb
    MYSQL_USER: notify
    MYSQL_PASSWORD: notify123
  ports:
    - "3306:3306"
  volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata:
